<a href="https://colab.research.google.com/github/spiegel-jpg/Denial_of_Service-8240/blob/main/CSCI8240RP_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import matplotlib.pyplot as plt
import numpy as np
from numpy.random import choice
from scipy.stats import norm
import statistics
from google.colab import drive
import pandas as pd
import plotly.express as px
import math
import pywt

In [6]:
drive.mount('/content/drive') # Mounting the drive

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [7]:
proj_dir = '/content/drive/MyDrive/spiegel'

In [8]:
data = pd.read_excel(proj_dir+'/get1.xlsx') # Reading the data

In [9]:
data['Time'] = data['Time'].dt.floor('h')
timeseries = data.set_index('Time')

In [10]:
H = 10633   
trH,tsH = int(H/2), int(H/2)                       # Total hours of data we have
pages = pd.read_csv(proj_dir+'/pages.csv')
valid_page = pages['PATH']

In [11]:
pages = pd.read_csv(proj_dir+'/pages.csv')
valid_page = pages['PATH']

# Creating quantiles with 114 pages each.

quantile = list(valid_page)
# quantile2 = list(valid_page[114:228])
# quantile3 = list(valid_page[228:342])
# quantile4 = list(valid_page[342:456])
# quantile5 = list(valid_page[456:570])

In [12]:
valid_page_checker = set(valid_page)
N = len(pages)                      # N is the total pages on the website
                                    # These are all the pages which are services with 200 HTML status code
M = int(5)
no_of_quantiles = int(N/M)

#  fij represent the total number of requests on ith page (1 ≤ i ≤ N) in the jth hour.


In [13]:
# U is the quantiles 
# timeseries.index[i]
time=set()
for i in range(len(timeseries)):
  time.add(timeseries.index[i])
time = list(sorted(time))
# print(time)
# U = [[0 for i in range(M)] for j in range(int(no_of_quantiles))]
# for i in range(int(no_of_quantiles)):
#   for j in range(M):
#     U[i][j]
print(len(time))

10633


In [14]:
# S = [[0 for i in range(trH)] for j in range(int(M))]
# T = [[0 for i in range(tsH)] for j in range(int(M))]
S = [0 for i in range(trH)]
T = [0 for i in range(tsH)]


In [15]:
for i in range(trH):
  requests = timeseries.loc[time[i]]
  no_of_req = int(len(requests))
  request_path = requests['Path']
  request_response = requests['Response']
  if not isinstance(requests, pd.DataFrame):
    if request_response == 200:
        if request_path in quantile:
          S[i]+=1
        # elif request_path in quantile2:
        #   S[1][i]+=1
        # elif request_path in quantile3:
        #   S[2][i]+=1
        # elif request_path in quantile4:
        #   S[3][i]+=1
        # elif request_path in quantile5:
        #   S[4][i]+=1
  else:
    for j in range(no_of_req):
      if request_response[j] == 200:
        if request_path[j] in quantile:
          S[i]+=1
        # elif request_path[j] in quantile2:
        #   S[1][i]+=1
        # elif request_path[j] in quantile3:
        #   S[2][i]+=1
        # elif request_path[j] in quantile4:
        #   S[3][i]+=1
        # elif request_path[j] in quantile5:
        #   S[4][i]+=1
# plt.plot(np.arange(0,tsH,1),S[4])

In [16]:
for i in range(trH,H-1,1):
  requests = timeseries.loc[time[i]]
  no_of_req = int(len(requests))
  request_path = requests['Path']
  request_response = requests['Response']
  if not isinstance(requests, pd.DataFrame):
    if request_response == 200:
        if request_path in quantile:
          T[i-trH]+=1
        # elif request_path in quantile2:
        #   T[1][i-trH]+=1
        # elif request_path in quantile3:
        #   T[2][i-trH]+=1
        # elif request_path in quantile4:
        #   T[3][i-trH]+=1
        # elif request_path in quantile5:
        #   T[4][i-trH]+=1
  else:
    for j in range(no_of_req):
      if request_response[j] == 200:
        if request_path[j] in quantile:
          T[i-trH]+=1
        # elif request_path[j] in quantile2:
        #   T[1][i-trH]+=1
        # elif request_path[j] in quantile3:
        #   T[2][i-trH]+=1
        # elif request_path[j] in quantile4:
        #   T[3][i-trH]+=1
        # elif request_path[j] in quantile5:
        #   T[4][i-trH]+=1
# plt.plot(np.arange(0,tsH,1),T[3])

In [17]:
half = math.floor(len(S)/2)
half_close = math.floor(0.9*len(S))
print(half,half_close,trH,tsH)

2658 4784 5316 5316


For Noise


Rtotal is the total number of requests for H/2 h. Hence, Rtotal is 129616 requests.

In [18]:
R_total_no = int(trH/2)
noise = S[0:R_total_no]
# noise2 = S[1][0:R_total_no]
# noise3 = S[2][0:R_total_no]
# noise4 = S[3][0:R_total_no]
# noise5 = S[4][0:R_total_no]
# noise = (noise1+noise2+noise3+noise4+noise5)

In [19]:
# Getting the Mean 
# noise1_mean = np.mean(noise1)
# noise2_mean = np.mean(noise2)
# noise3_mean = np.mean(noise3)
# noise4_mean = np.mean(noise4)
# noise5_mean = np.mean(noise5)
# # Getting the Variance
# noise1_var = np.var(noise1)
# noise2_var = np.var(noise2)
# noise3_var = np.var(noise3)
# noise4_var = np.var(noise4)
# noise5_var = np.var(noise5)
# Getting mean and variance for all quantiles
noise_mean = np.mean(noise)
noise_var = np.var(noise)
print(noise_mean, noise_var)

20.224228743416102 1449.5975770011


In [20]:
T_R_total_no = int(trH/2)
Tnoise = T[0:T_R_total_no]
# Tnoise2 = T[1][0:T_R_total_no]
# Tnoise3 = T[2][0:T_R_total_no]
# Tnoise4 = T[3][0:T_R_total_no]
# Tnoise5 = T[4][0:T_R_total_no]
# Tnoise = (Tnoise1+Tnoise2+Tnoise3+Tnoise4+Tnoise5)

In [21]:
# Getting the Mean 
# Tnoise1_mean = np.mean(Tnoise1)
# Tnoise2_mean = np.mean(Tnoise2)
# Tnoise3_mean = np.mean(Tnoise3)
# Tnoise4_mean = np.mean(Tnoise4)
# Tnoise5_mean = np.mean(Tnoise5)
# # Getting the Variance
# Tnoise1_var = np.var(Tnoise1)
# Tnoise2_var = np.var(Tnoise2)
# Tnoise3_var = np.var(Tnoise3)
# Tnoise4_var = np.var(Tnoise4)
# Tnoise5_var = np.var(Tnoise5)
# Getting mean and variance for all quantiles
Tnoise_mean = np.mean(Tnoise)
Tnoise_var = np.var(Tnoise)
print(Tnoise_mean, Tnoise_var)

13.747178329571106 1314.431942752999


In [22]:
# Normal distribution for one of the quantiles according to the formula in the paper.
x = np.arange(-R_total_no, R_total_no, 1)
p=0.2 # 0.03 0.05 0.1 0.15 0.2
# plt.plot(x,norm.pdf(x,p*noise_mean,p*noise_var))
# we havent used normal distribution in our paper as the paper says to add random noise but the normal distribution is will add a bell shaped curve
# instead we took the approach of adding noise at random intervals with requests being added at a probability corresponding to the mean of the request for that quantile 

In [23]:
# S0_40noise = S[0][5316:9570]+A_noise3
# S0_paper_noise=[]
# for i in range(H):
#   if i<5317 or i>9569:
#     S0_paper_noise.append(S[0][i])
#   elif i>5316 and i<9570:
#     S0_paper_noise.append(S0_40noise[i-5317])
# df = pd.DataFrame(dict(
#     x = np.arange(0,H,1),
#     y = np.array(S0_paper_noise)
# ))
# fig = px.line(df, x="x", y="y", title="Quantile 1 With added noise according to papers FRC attack") 
# fig.show(0)
# x = np.arange(0,H,1)
# y = np.array(S0_paper_noise)-np.array(S[0])
# plt.title('Quantile 1 noise 10% attack')
# plt.plot(x,y)

### **Here starts the real thing (Graph)**




In [24]:
# Quantile 1 with added noise
from scipy.stats import gamma
P=0.02
# noise1_prob = poisson.rvs(mu=noise1_mean,size=math.floor(noise1_mean+P*noise1_var)) 
noise1_prob = gamma.rvs(a=(noise_mean), size=math.floor(noise_mean+P*noise_var))
noise1_prob = noise1_prob/sum(noise1_prob)
quantile1_req_noise=[]
# quantile1_prob_noise=[]

for i in range(math.floor(noise_mean+P*noise_var)):
  quantile1_req_noise.append(i)

noise1_data = choice(quantile1_req_noise, half_close-half, p=noise1_prob) # noise
S_mod = noise1_data + S[half:half_close]
S0=list()  # sequence 0 with added noise
for i in range(trH):
  if i<half:
    S0.append(S[i])
  elif i>=half and i<half_close:
    S0.append(S_mod[i-half])
  elif i>=half_close:
    S0.append(S[i])
df = pd.DataFrame(dict(
    x = np.arange(0,trH,1),
    y = np.array(S0)
))
df1 = pd.DataFrame(dict(
    x = np.arange(0,trH,1),
    y = np.array(S0)-np.array(S)
))

# new_df = df - df_no_noise
fig = px.line(df, x="x", y="y", title="Quantile 1 With added noise") 
fig.add_vrect(x0=half, x1=half_close)
fig.show(0)
fig1 = px.line(df1, x="x", y="y", title="Quantile 1 noise") 
fig1.add_vrect(x0=half, x1=half_close)
fig1.show(0)
# plt.plot(np.arange(0,H,1), S0)


In [25]:
print("Darpan The Dirbuster")

Darpan The Dirbuster


In [26]:
target_seq = list()
for i in range(trH):
  if i<half:
    target_seq.append(0)
  elif i>=half and i<half_close:
    target_seq.append(1)
  elif i>=half_close:
    target_seq.append(0)
df = pd.DataFrame(dict(
    x = np.arange(0,trH,1),
    y = target_seq
))
targetSequence=np.array(target_seq)
fig = px.line(df, x="x", y="y", title="Target sequence") 
fig.show(0)

**Thus we have added noise to the data with a probability distribution depending on the data from the first 50% data range. We have currently not accounted the different attack percentages as it is still unclear with our own implementation.**

In [27]:
print(pywt.families(short=False))
wavelet = pywt.Wavelet('db4')
print(wavelet)

['Haar', 'Daubechies', 'Symlets', 'Coiflets', 'Biorthogonal', 'Reverse biorthogonal', 'Discrete Meyer (FIR Approximation)', 'Gaussian', 'Mexican hat wavelet', 'Morlet wavelet', 'Complex Gaussian wavelets', 'Shannon wavelets', 'Frequency B-Spline wavelets', 'Complex Morlet wavelets']
Wavelet db4
  Family name:    Daubechies
  Short name:     db
  Filters length: 8
  Orthogonal:     True
  Biorthogonal:   True
  Symmetry:       asymmetric
  DWT:            True
  CWT:            False


In [30]:
a,d = pywt.dwt(S0,'db4')
d.fill(0)
S0r = pywt.idwt(a,d,'db4')
for i in range(5):
  a,d = pywt.dwt(S0r,'db4')
  d.fill(0);
  S0r = pywt.idwt(a,d,'db4')


for i in range(len(S0r)):
  if S0r[i]<=0:
    S0r[i]=0

df = pd.DataFrame(dict(
    x = np.arange(0,trH,1),
    y = S0r
))
fig = px.line(df, x="x", y="y", title="Denoise S0") 
fig.add_vrect(x0=half, x1=half_close)
fig.show(0)

LSTM Implementation

In [ ]:
# Dk1 Dk2 Dk3 Dk4 Dk5 are the final sequences to be fed into the network 
# all combined make the signal and should give us 1 model
# target


In [ ]:
import tensorflow as tf 
from tensorflow import keras 
from tensorflow.keras import layers 
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [ ]:
model = Sequential()
model.add(LSTM(4, return_sequences=True, input_shape=(12,1), dropout=0.1))
model.add(LSTM(512, return_sequences=True, dropout=0.1))
model.add(LSTM(256, return_sequences=True, dropout=0.1))
model.add(LSTM(64, dropout=0.1))
model.add(Dense(1, activation="sigmoid"))
model.compile(
    loss=keras.losses.BinaryCrossentropy(from_logits=False),
    optimizer='adam'
)

In [ ]:
X = np.array(np.floor(S0r))
# samples.append(sample)
dtarget = np.array(targetSequence[0:5304])
# X = np.array(samples)
# X=X.reshape(len(x),5,1)
# print(X.shape)

In [ ]:
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [ ]:
X,y = split_sequence(X, 12)

In [ ]:
X = X.reshape((X.shape[0], X.shape[1], 1))
print(X[:3])

[[[ 52.]
  [ 11.]
  [  2.]
  [ 13.]
  [ 40.]
  [ 98.]
  [116.]
  [ 92.]
  [ 81.]
  [ 69.]
  [ 64.]
  [ 75.]]

 [[ 11.]
  [  2.]
  [ 13.]
  [ 40.]
  [ 98.]
  [116.]
  [ 92.]
  [ 81.]
  [ 69.]
  [ 64.]
  [ 75.]
  [ 73.]]

 [[  2.]
  [ 13.]
  [ 40.]
  [ 98.]
  [116.]
  [ 92.]
  [ 81.]
  [ 69.]
  [ 64.]
  [ 75.]
  [ 73.]
  [ 62.]]]


In [ ]:
from keras.datasets import imdb
top_words = 5000
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=top_words)

17473536/17464789 [==============================] - 0s 0us/step


In [ ]:
from keras.layers.embeddings import Embedding


In [ ]:
history = model.fit(X,y, epochs=10, batch_size=32,shuffle=False)

Epoch 1/10


ValueError: ignored

In [ ]:
loss = model.evaluate(X, dtarget, verbose=0)

In [ ]:
print(loss)

In [ ]:
predictions = model.predict(X, verbose=0)

In [ ]:
import pickle
saved_models_1 = pickle.dumps(model)

In [ ]:
predict = predictions.flatten()
df = pd.DataFrame(dict(
    x = np.arange(0,H,1),
    y = np.array(predict)
))

fig = px.line(df, x="x", y="y", title="Target sequence") 
fig.add_vrect(x0=5316, x1=9570)
fig.show(0)

In [ ]:
samplesp=list()
for i in range(0,H):
  samplep = [100,10,2,1,0]
  samplesp.append(samplep)
samplesp=np.array(samplesp)
samplesp = samplesp.reshape(len(samplesp),5,1)
predictthis = model.predict(samplesp)
predict = predictions.flatten()
df = pd.DataFrame(dict(
    x = np.arange(0,H,1),
    y = np.array(predict)
))

fig = px.line(df, x="x", y="y", title="Target sequence") 
fig.add_vrect(x0=5316, x1=9570)
fig.show(0)